apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-jumphost-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-jumphost
  template:
    metadata:
      labels:
        app: prod-jumphost
    spec:
      containers:
      - name: prod-jumphost
        image: debian
        command: ['sleep', 'infinity']
        resources:
          requests:
            memory: "1m"
            cpu: "1m"
        

